config/routes.rb
Gearlance::Application.routes.draw do
  resources :reviews
  resources :subcategories
  get "/categories/:slug/:sub_category" => "subcategories#index"


  resources :tests


  root :to => "items#featured", as: "featured"

  resources :categories
  resources :items
  resources :users
  resources :reservations, except: [:new] do
    resources :charges
  end
  resource :session, except: [:edit]

  match "/faq" => "pages#faq"
  match "/about" => "pages#about"
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  attr_accessible :category_id, :subname

  belongs_to :category
  has_many :items

end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all
    @categories = Category.all
    @subcat = Subcategory.find_by_subname(params[:sub_category])
    @items = Item.where(:subcategory_id => @subcat.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subcategories }
    end
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
    @subcategory = Subcategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subcategory }
    end
  end

  # GET /subcategories/new
  # GET /subcategories/new.json
  def new
    @subcategory = Subcategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subcategory }
    end
  end

  # GET /subcategories/1/edit
  def edit
    @subcategory = Subcategory.find(params[:id])
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(params[:subcategory])

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully created.' }
        format.json { render json: @subcategory, status: :created, location: @subcategory }
      else
        format.html { render action: "new" }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subcategories/1
  # PUT /subcategories/1.json
  def update
    @subcategory = Subcategory.find(params[:id])

    respond_to do |format|
      if @subcategory.update_attributes(params[:subcategory])
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory = Subcategory.find(params[:id])
    @subcategory.destroy

    respond_to do |format|
      format.html { redirect_to subcategories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subname %><br />
    <%= f.text_field :subname %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing subcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<div class="row-fluid">
  <h1 class="withsubhead">Browse Gear.</h1>
  <h3>Try out gear from people like you.</h3>
</div>

<div class="row-fluid">
  <div class="span4 well">

      <%= notice %>

      <ul class="nav nav-list">  <!-- Categories list -->
        <li class="nav-header">Categories</li>
        <% @categories.each do |category| %>
          <li>
            <%= link_to category.slug.capitalize, category_url(category.slug) %>
            <% if category.subcategories.present? %>
              <ul class="sub_categories">
                <% category.subcategories.each do |subcat| %>
                   <li><%= link_to subcat.subname, category_url("#{category.slug}/#{subcat.subname}") %></li>
                <% end %>
              </ul>
            <% end %>
          </li>
        <% end %>
      </ul>

  </div>

  <div class="span8">
    <% if @items.count == 0 %>
      We're sorry.  Currently there are no <%= @subcat.subname.pluralize %> available for rent.
    <% end %>
    <ul class="browse">
        <% @items.each do |item| %>
          <li class="item-list">
            <div class="row browse">
              <div class="span4">
                <% if item.image_content_type.present? || item.photo_url.present? %>
                  <% if item.image_content_type.present?  %>
                  <%= link_to image_tag(item.image.url(:small)), item_url(item.id) %>
                  <% else %>
                  <%= link_to image_tag(item.photo_url, class: "browse-image"), item_url(item.id) %>
                  <% end %>
                <% else %>
                  <%= link_to image_tag "http://www.clker.com/cliparts/J/P/C/M/k/d/teal-camera-md.png" %>
                <% end %>
              </div>
              <div class="span8 browse">
                <h3><%= link_to item.name, item_url(item.id) %></h3>
                <p><%= item.description[0..160] %>...</p>

                <p><b>Daily:</b> $<%= item.daily_price %> | <b>Weekly:</b> $<%= item.weekly_price %> | <b>Monthly:</b> $<%= item.monthly_price %></p>
                <div class="browse-buttons">
                  <% if signed_in? && item.user_id == current_user.id %>
                    <%= link_to "View", item_url(item.id), class: "btn" %> &nbsp;|&nbsp;
                    <%= link_to "Edit", edit_item_url(item.id), class: "btn" %> &nbsp;|&nbsp;
                    <%= link_to "Delete", item_url(item.id), method: :delete, confirm: "Do you really want to remove your #{item.name} and miss out on the opportunity to earn extra income?", class: "btn btn-danger" %>
                  <% else %>
                    <%= link_to "Reserve", item_url(item.id), class: "btn btn-primary" %>
                  <% end %>
                </p>
              </div>
            </div>

          </li>

        <% end %>
        </ul>
    </div>

</div>

app/views/subcategories/new.html.erb
<h1>New subcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subname:</b>
  <%= @subcategory.subname %>
</p>

<p>
  <b>Category:</b>
  <%= @subcategory.category_id %>
</p>


<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Back', subcategories_path %>