config/routes.rb
Gearlance::Application.routes.draw do
  resources :reviews
  resources :subcategories
  get "/categories/:slug/:sub_category" => "subcategories#index"


  resources :tests


  root :to => "items#featured", as: "featured"

  resources :categories
  resources :items
  resources :users
  resources :reservations, except: [:new] do
    resources :charges
  end
  resource :session, except: [:edit]

  match "/faq" => "pages#faq"
  match "/about" => "pages#about"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation, :avatar, :phone, :address_1, :address_2, :city, :state, :zip, :country, :user_bio
  has_attached_file :avatar, :styles => { small: '150x150>' }

  has_secure_password

  has_many :items
  has_many :reservations
  has_many :reviews

  # validates_attachment_presence :image
  validates_attachment_size :avatar, :less_than => 5.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']

  validates :email, :first_name, :last_name, :password, presence: true
  validates :email, uniqueness: true
  validates :password, length: { within: 4..15 }
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def average_rating
    ratings = []

    self.reviews.each do |user|
      ratings << user.rating
    end

    sum = 0.0
    ratings.each do |rating|
      sum += rating
    end

    if ratings.count == 0.0
      0.0
    else
       (sum/(ratings.count)).round(1)
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorized_to_view_user, only: [:show]
  before_filter :is_admin, only: [:index]

  def authorized_to_view_user
    if !signed_in?
      redirect_to new_session_url,
      notice: "You need to be logged in to view this user."
    end
  end

  def is_admin
    if !signed_in? || signed_in? && current_user.admin != true
      redirect_to items_url
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.email = @user.email.downcase

    if @user.save
      UserMailer.welcome_email(@user).deliver
      session[:user_id] = @user.id
      redirect_to user_url(session[:user_id]), notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def index
    @user = User.all
  end

  def show
    @user = User.find_by_id(params[:id])

  end

  def edit
    @user = User.find_by_id(session[:user_id])
  end

  def update
    @user = User.find_by_id(session[:user_id])
    @user.update_attributes(params[:user])

    if @user.save
      redirect_to user_url(session[:user_id])
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(session[:user_id])
    @user.destroy
    reset_session

    redirect_to items_url
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: "#{user.first_name} #{user.last_name}" , class: "gravatar")
  end

end

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>
<% if @user.errors.full_messages.present?  %>
  <%= @user.errors.full_messages %>
<% end %>

<div class="row">

<%= form_for @user do |f| %>

  <div class="span3 offset1">
      <ul class="thumbnails">
        <li class="span3">
          <div class="thumbnail">
            <% if @user.avatar.present? %>
              <%= image_tag @user.avatar, width:260, class: "thumbnail" %><br>
            <% else %>
              <%= gravatar_for @user, 260 %><br>
            <% end %>
            <div class="fileinputs">
              <%= f.file_field :avatar, class: "btn file" %>
              <div class="fakefile">
                <input type="file" class="upload" />
                <img src="/assets/upload-photo.png" />
              </div>
            </div>
          </div>
        </li>
      </ul>
  </div>

  <div class="span3 well">

<legend>Account</legend>

  <%= f.label :first_name, "First Name" %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name, "Last Name" %>
  <%= f.text_field :last_name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Password Confirmation" %>
  <%= f.password_field :password_confirmation %>

  </div>

  <div class="span3 well">
<!--
  <%= f.label :avatar, "Avatar Photo" %>
  <%= f.text_field :avatar %> -->

<legend>Contact</legend>

  <%= f.label :phone, "Phone" %>
  <%= f.text_field :phone %>
  <i class="icon-search"></i>

  <%= f.label :address_1, "Address" %>
  <%= f.text_field :address_1 %>

  <%= f.label :address_2, "Address 2" %>
  <%= f.text_field :address_2 %>

  <%= f.label :city, "City" %>
  <%= f.text_field :city %>

  <%= f.label :state, "State" %>
  <%= f.text_field :state %>

  <%= f.label :zip, "Zip" %>
  <%= f.text_field :zip %>

  <%= f.label :country, "Country" %>
  <%= f.text_field :country %>

  <%= f.label :user_bio, "Say something nice about yourself" %>
  <%= f.text_area :user_bio, rows: "5" %>

  <br><%= f.submit "Update Profile", class: "btn btn-success" %>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<% if notice %>
  <p><%= notice %></p>
<% end %>

    <% @user.each do |user| %>
      <ul>
        <li>
          <p><b>First Name:</b> <%= link_to user.first_name, user_url(user.id) %></p>
          <p><b>Last Name:</b> <%= user.last_name %></p>
          <p><b>Email:</b> <%= user.email %></p>
        </li>
      </ul>

    <% end %>

app/views/users/new.html.erb
<div class="span6 center">

  <h1 class="text-center">Join Gearlance!</h1>

  <%= form_for @user do |f| %>

    <div class="row">
      <div class="span3">
        <ul class="thumbnails">
          <li class="span3">
            <div class="thumbnail">
              <img src="/assets/default-profile.jpg" alt="">
              <div class="fileinputs">
                <%= f.file_field :avatar, class: "btn file" %>
                <div class="fakefile">
                  <input type="file" class="upload" />
                  <img src="/assets/upload-photo.png" />
                </div><!-- end fakefile -->
              </div><!-- end fileinputs -->
            </div><!-- end thumbnail -->
          </li>
        </ul>
      </div><!-- end span3 -->

      <div class="span3">

        <%= f.text_field :email, placeholder: "Email" %>
        <% if @user.errors[:email].any? %>
          Email <%= @user.errors[:email][0] %>
        <% end %>

        <%= f.text_field :first_name, placeholder: "First Name" %>
        <% if @user.errors[:first_name].any? %>
          We need a first name
        <% end %>

        <%= f.text_field :last_name, placeholder: "Last Name" %>
        <% if @user.errors[:last_name].any? %>
          We need a last name for that first name
        <% end %>

        <%= f.password_field :password, placeholder: "Password"%>
        <% if @user.errors[:password].any? %>
          <% if @user.errors[:password][0].present? %>
            Password <%= @user.errors[:password][0] %><br>
          <% end %>
          <% if @user.errors[:password][1].present? %>
            Password <%= @user.errors[:password][1] %>
          <% end %>
        <% end %>

        <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>

        <br><%= f.submit "Sign Up", class: "btn btn-success" %>
      </div> <!-- end span3 -->
   <% end %>

  </div> <!-- row -->
</div><!-- end center -->

app/views/users/show.html.erb
<% if @user.id == session[:user_id] %>
<div class="row-fluid">
  <ul class="nav nav-pills span12">
   <li class="active">
    <a href="#">Dashboard</a>
  </li>
  <li><%= link_to "Reservations", reservations_url %></li>
  <li class="dropdown">
    <a class="dropdown-toggle"
       data-toggle="dropdown"
       href="#">
        Account
        <b class="caret"></b>
      </a>
    <ul class="dropdown-menu">
      <li><a href="#">Notifications</a></li>
      <li><a href="#">Payout Preferences</a></li>
      <li><a href="#">Transaction History</a></li>
      <li><a href="#">Referrals</a></li>
    </ul>
  </li>
</ul>
</div>
<% end %>

<div class="row-fluid">
<div class="span3 well">

    <% if @user.avatar.present? %>
    <%= image_tag @user.avatar, width:260, class: "thumbnail" %><br>
      <% else %>
        <%= gravatar_for @user, 260 %><br>
      <% end %>
    <!-- <h1><%= @user.first_name %> <%= @user.last_name %></h1> -->

<div class="text-center">
  <h3><%= @user.first_name %> <%= @user.last_name %></h3>
  <h5><%= @user.city %>, <%= @user.state %></h5>
  <h6>Gearlance Rating: <%= @user.average_rating %> / 5.0</h6>
  <h6>Reviews: <%= @user.reviews.count %></h6>
<!-- <dl class="dl-horizontal">
  <dt>Name</dt>
  <dd><%= @user.first_name %> <%= @user.last_name %></dd>
  <dt>Email</dt>
  <dd><%= @user.email %><dd>
  <dt>Phone</dt>
  <dd><%= @user.phone %></dd>
</dl> -->
<% if @user.id == session[:user_id] %>
<%= link_to "Edit my profile", edit_user_url(@user.id) %>
<% end %>
</div>
</div>

<!-- <ul>
  <li><b>Name:</b> <%= @user.first_name %> <%= @user.last_name %></li>
  <li><b>Email:</b> <%= @user.email %></li>
  <li><b>Phone:</b> <%= @user.phone %></li>
  <li><b>Address:</b> <%= @user.address_1 %></li>
  <li><b>Address:</b> <%= @user.address_2 %></li>
  <li><b>City:</b> <%= @user.city %></li>
  <li><b>State:</b> <%= @user.state %></li>
  <li><b>Zip:</b> <%= @user.zip %></li>
  <li><b>Country:</b> <%= @user.country %></li>
</ul>
  <%= link_to "Edit my profile", edit_user_url(@user.id) %>
  <%= link_to "Delete my profile", user_url(@user.id), method: :delete, confirm: "Sure?" %> -->



<div class="span8 item-list">
<% if @user.id == session[:user_id] %>
<legend>Your Gear</legend>
<% end %>
<% if @user.items.count > 0 %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Item</th>
        <th>Category</th>
        <th>Type</th>
        <th>Name</th>
        <!-- <th>Description</th> -->
        <th>Daily Price</th>
        <th>Weekly Price</th>
        <th>Monthly Price</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @user.items.each do |item| %>
        <tr id="row_<%= item.id %>">
          <td><% if item.image_content_type.present? || item.photo_url.present? %>
                <% if item.image_content_type.present?  %>
                <%= link_to image_tag(item.image.url(:small)), item_url(item.id) %>
              <% else %>
                <%= link_to image_tag(item.photo_url), item_url(item.id) %>
              <% end %>
            <% else %>
             <%= link_to image_tag "http://www.clker.com/cliparts/J/P/C/M/k/d/teal-camera-md.png" %>
          <% end %>
          </td>
          <td><%= item.category.name %></td>
          <td><%= item.subcategory.subname %></td>
          <td><%= item.name %></td>
          <!-- <td><%= item.description %></td> -->
          <td>$<%= item.daily_price %></td>
          <td>$<%= item.weekly_price %></td>
          <td>$<%= item.monthly_price %></td>
          <td><%= link_to 'Show', item, class: 'btn btn-primary' %></td>
          <% if @user.id == session[:user_id] %>
            <td><%= link_to 'Edit', edit_item_url(item), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Delete', item, class: 'btn btn-danger', method: 'delete', data: { confirm: "Do you really want to remove your #{item.name} and miss out on the opportunity to earn extra income?" }, remote: true %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "List more gear", new_item_url %>
<% elsif @user.id == session[:user_id] %>
  <h4>You're not listing any gear.  Bummer.</h4>
  <%= link_to "List your gear", new_item_url, class: "btn btn-primary", style: "margin: 15px 0" %>
<% else %>

<% end %>


<!--
<legend>Your Reservations</legend>
<% if @user.reservations.present? %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Category</th>
        <th>Name</th>
        <th>Description</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Rental Days</th>
        <th>Estimate</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    <% @user.reservations.each do |r| %>
      <tr>
          <td><%= r.id %></td>
          <td><%= r.item.category.name %></td>
          <td><%= r.item.name %></td>
          <td><%= r.item.description %></td>
          <td><%= r.start_date.strftime("%A %b %d, %Y") %></td>
          <td><%= r.end_date.strftime("%A %b %d, %Y") %></td>
          <td><%= r.rental_period %></td>
          <td>$ <%= r.estimate %></td>

          <td><%= link_to 'Show', reservation_url(r.id), class: 'btn btn-primary' %></td>
          <% if @user.id == session[:user_id] %>
            <td><%= link_to 'Edit', edit_reservation_url(r.id), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Cancel', reservation_url(r.id), class: 'btn btn-danger', method: 'delete', data: { confirm: "Do you really want to delete this reservation?" } %></td>
          <% end %>
        <% end %><br>
      </tr>
    </tbody>
  </table>
  <% elsif @user.id == session[:user_id] %>
  <h4>You have no reservations.</h4>
  <%= link_to "Browse Gear", new_item_url, class: "btn" %>
<% else %>

<% end %> -->

</div><!-- span -->


</div><!-- row -->