config/routes.rb
Gearlance::Application.routes.draw do
  resources :reviews
  resources :subcategories
  get "/categories/:slug/:sub_category" => "subcategories#index"


  resources :tests


  root :to => "items#featured", as: "featured"

  resources :categories
  resources :items
  resources :users
  resources :reservations, except: [:new] do
    resources :charges
  end
  resource :session, except: [:edit]

  match "/faq" => "pages#faq"
  match "/about" => "pages#about"
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :category_id, :user_id, :name, :photo_url, :description, :daily_price, :weekly_price, :monthly_price, :category_slug, :image, :subcategory_id
  attr_accessible :reservations_attributes
  has_attached_file :image, :styles => { small: '150x150>' }
                    # :url => "/assets/items/:id/:style/:basename.:extension",
                    # :path => ":rails_root/public/assets/items/:id/:style/:basename.:extension"

  belongs_to :category
  belongs_to :subcategory
  belongs_to :user
  has_many :reservations
  has_many :reviews

  accepts_nested_attributes_for :reservations, allow_destroy: true

  # validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/pdf']

  validates :category_id, :user_id, :name, :description, :daily_price, :weekly_price, :monthly_price, presence: true

  def item_average_rating
    ratings = []

    self.reviews.each do |user|
      ratings << user.rating
    end

    sum = 0.0
    ratings.each do |rating|
      sum += rating
    end

    if ratings.count == 0.0
      0.0
    else
       (sum/(ratings.count)).round(1)
    end
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authorize_user, only: [:new, :edit, :destroy]

  def authorize_user
    if !signed_in?
      redirect_to new_session_url,
      notice: "You need to be logged in to add a new item."
    end
  end

  def featured
    @items = Item.all
  end

  def new
    @categories = Category.all
    @subcategories = Subcategory.all
    @item = Item.new
  end

  def create
    if params[:category_name].present? # pull out params() to a variable and work with it
      name = params[:category_name]
      c = Category.create(name: name.singularize, slug: name.downcase.pluralize)
      params[:item][:category_id] = c.id
    end

    if params[:subcategory_subname].present? # pull out params() to a variable and work with it
      subname = params[:subcategory_subname]
      sc = Subcategory.create(subname: subname.singularize, slug: subname.downcase.pluralize)
      params[:item][:subcategory_id] = sc.id
    end


    @item = Item.new(params[:item])
    @item.user_id = session[:user_id]

    if @item.save
      redirect_to user_url(session[:user_id]), notice: "You added an item!"
    else
      render "new"
    end
  end

  def index
    @items = Item.page(params[:page]).per(10)
    @categories = Category.all
  end

  def show
    @item = Item.find_by_id(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @item = Item.find_by_id(params[:id])

    @categories = Category.all
  end

  def update
    i = Item.find_by_id(params[:id])
    i.update_attributes(params[:item])
    i.save

    redirect_to item_url(i)
  end

  def destroy
    @item = Item.find_by_id(params[:id])
    id = @item.user.id
    @item.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to user_url(id) }
    end
  end
end

app/views/items/_date.html.erb
<%= form_for Reservation.new do |r| %>

  <%= r.hidden_field :user_id, value: session[:user_id] %>
  <%= r.hidden_field :item_id, value: @item.id %>

  <%= r.label :from %>
  <%= r.text_field :start_date, value: Date.today  %>

  <%= r.label :to %>
  <%= r.text_field :end_date, value: Date.tomorrow %>

  <br><br>
  <p>Does that work for you?</p>
  <%= r.text_area :comments, placeholder: "Say something nice...", rows: 3 %>

  <br><br>
  <p>
    <%= r.submit "Send Request", class: "btn btn-success", remote: true %>
  </p>

<% end %>

app/views/items/_form.html.erb
<%= form_for @item, :html => { :multipart => true } do |f| %>
<div class="row">
<div class="span4">
  <div>

    <% if @item.image_content_type.present? || @item.photo_url.present? %>
      <% if @item.image_content_type.present?  %>
      <%= link_to image_tag(@item.image.url(:small)), item_url(@item.id) %>
      <% else %>
      <%= link_to image_tag(@item.photo_url, class: "browse-image"), item_url(@item.id) %>
      <% end %>
    <% else %>
      <%= link_to image_tag "http://www.clker.com/cliparts/J/P/C/M/k/d/teal-camera-md.png" %>
    <% end %>


    <%= f.file_field :image %>
  </div>

</div>

<div class="span3">
  <% if @item.errors.any? %>
    <p>Oh no! Let's refactor that Item.</p>
  <% end %>

  <%= f.label :category_id, "Select a Category" %>
  <%= f.collection_select(:category_id, Category.all, :id, :name, prompt: "[Select One]") %>
  <% if @item.errors[:category_id].any? %>
    required
  <% end %>

  <%= f.label :subcategory_id, "More specifically?" %>
  <%= f.grouped_collection_select :subcategory_id, Category.all, :subcategories, :name, :id, :subname, prompt: "[Select One]" %>

  <%= f.label :name, "Item Title" %>
  <%= f.text_field :name %>
  <% if @item.errors[:name].any? %>
    required
  <% end %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description, rows: "7" %>
  <% if @item.errors[:description].any? %>
    required
  <% end %>

</div>

<div class="span3">
  <%= f.label :daily_price, "Daily Price" %>
  <%= f.number_field :daily_price, placeholder: "$0.00" %>
  <% if @item.errors[:daily_price].any? %>
    required
  <% end %>

  <%= f.label :weekly_price, "Weekly Price" %>
  <%= f.number_field :weekly_price, placeholder: "$0.00" %>
  <% if @item.errors[:weekly_price].any? %>
    required
  <% end %>

  <%= f.label :monthly_price, "Monthly Price" %>
  <%= f.number_field :monthly_price, placeholder: "$0.00" %>
  <% if @item.errors[:monthly_price].any? %>
    required
  <% end %>

  <br><%= f.submit class: "btn btn-success" %>
<% end %>
</div>
</div>


<script>
  $(document).ready(function(){
    var subcategory = $('#item_subcategory_id').html();
    console.log(subcategory)
  $('#item_category_id').change(function(){
    var selected_category = $('#item_category_id :checked').text();

    var filtered_subcategories = $(subcategory).filter('optgroup[label="' + selected_category + '"]').html();
    console.log(filtered_subcategories);
    $('#item_subcategory_id').html(filtered_subcategories).prepend('option[value="Select One"]').html;
    })
  });
</script>

app/views/items/destroy.js.erb
$('#row_<%= @item.id %>').fadeOut(1000).slideUp();

app/views/items/edit.html.erb
<h1>Edit <%= @item.name %></h1>

<%= link_to raw("&laquo; Back"), item_url(@item.id), class: "btn" %><br><br>

<%= render 'form' %>

app/views/items/featured.html.erb
  <div class="row-fluid">
    <div class="span12 hero">
      <img src="" class="hero-image"/>
      <div class="headliner">
        <h1>Rent Gear today</h1>
        <h4>Easily try out cameras, lenses, lights </br>and more from people just like you.</h4>
        <%= link_to "Browse Gear", items_url, class: "btn btn-success btn-large" %>
      </div>
    </div>
  </div>





    <div class="gallery-home center top-margin">
      <ul class="thumbnails grid">
        <li class="shadow">
          <a href="<%= item_url(3) %>" class="thumbnail">
            <div class="wrapper">
              <div class="card">
                <div class="face front">
                  <img src="http://images17.newegg.com/is/image/newegg/30-995-995-TS?$S300W$">
                </div>
                <div class="face back">
                  <ul>
                    <li><em>TAMRON 18-270mm Lens</em></li>
                    <li>Great for taking photos of the water or semi-still landscapes</li>
                    <li>$10/day</li>
                    <li><button class="btn btn-small pull-right">Rent</button></li>
                </div>
              </div>
            </div>
          </a>
        </li>
        <li class="shadow">
          <a href="<%= item_url(35) %>" class="thumbnail">
            <div class="wrapper">
              <div class="card">
                <div class="face front">
                  <img src="http://www.thelashop.com/images/P/01UMS002-VL-303UL-B-p01.jpg">
                </div>
                <div class="face back">
                  <ul>
                    <li><em>32 inch Umbrella Photo Lighting Continuous 3 Lights Kit with Case</em></li>
                    <li>Great for taking photos of the water or semi-still landscapes</li>
                    <li>$10/day</li>
                    <li><button class="btn btn-small pull-right">Rent</button></li>
                  </ul>
                </div>
              </div>
            </div>
          </a>
        </li>
        <li class="shadow">
          <a href="<%= item_url(58) %>" class="thumbnail">
            <div class="wrapper">
              <div class="card">
                <div class="face front">
                  <img src="https://lh6.googleusercontent.com/public/QLZkFlj5wpdxoxnxgqbZMkEIZJyT7fn9tZgPiikorkQ-6yEEgfniBl1Hjf-kbYpUZyGv1UHIzy1wvyZBCDRLT7GacKFShZO0vQXGsOKfrgnj58Y2sI6LX52676eh1qOTg8n8LfAsOQ8Dk21AvgS_mpFoog=s220-c">
                </div>
                <div class="face back">
                  <ul>
                    <li><em>Apogee Mic Studio Quality Microphone for iPad, Iphone and Mac</em></li>
                    <li>Great for taking photos of the water or semi-still landscapes</li>
                    <li>$10/day</li>
                    <li><button class="btn btn-small pull-right">Rent</button></li>
                  </ul>
                </div>
              </div>
            </div>
          </a>
        </li>
        <li class="shadow">
          <a href="<%= item_url(43) %>" class="thumbnail">
            <div class="wrapper">
              <div class="card">
                <div class="face front">
                  <img src="http://img1.targetimg1.com/wcsstore/TargetSAS//img/p/14/44/14449457_130307103000.jpg">
                </div>
                <div class="face back">
                  <ul>
                    <li><em>Nikon XB Lens</em></li>
                    <li>Great for taking photos of the water or semi-still landscapes</li>
                    <li>$10/day</li>
                    <li><button class="btn btn-small pull-right">Rent</button></li>
                  </ul>
                </div>
              </div>
            </div>
          </a>
        </li>
      </ul>
    </div>




  <div class="row">
    <div class="span9 center">
      <div id="myCarousel" class="carousel slide">
        <div class="row">
          <ol class="carousel-indicators span9 center">
            <li><a href="#" data-target="#myCarousel" data-slide-to="0">Want to make some extra money?</a></li>
            <li><a href="#" data-target="#myCarousel" data-slide-to="1">Need gear for a project?</a></li>
            <li><a href="#" data-target="#myCarousel" data-slide-to="2">Interested in new gear?</a></li>
          </ol>
        </div>
        <!-- Carousel items -->
        <div class="carousel-inner">
          <div class="item active">
            <div class="row gallery-info">
              <div class="span3 offset1">
                <img src="http://2.bp.blogspot.com/-MwIlpDCqbX0/TmIjim9nYjI/AAAAAAAAACo/PDIpIiFqzEM/s1600/camera-lens-icon.jpg" height="400px" width="300px">
              </div>
              <div class="span4 top-margin">
                <h2>Want to make some extra money?</h2>
                <h4>Rent out your gear when you're not using it. You don't use your gear 24/7, but that doesn't mean your gear can't work for you.  Make some extra cash by safely renting gear to trusted peers on Gearlance.</h4>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="row gallery-info">
              <div class="span3 offset1">
                <img src="http://a248.e.akamai.net/pix.crutchfield.com/ImageHandler/fixedscale/900/900/products/2013/2/280/x280HFR400-F.jpeg" height="400px" width="300px">
              </div>
              <div class="span4 top-margin">
                <h2>Need gear for a project?</h2>
                <h4>Rent gear from pros just like you and save a ton of money.</h4>
                  <p>Gearlance has gear up to 50% off of traditional rental houses.  Rent from your peers and be part of the community.</p>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="row gallery-info">
              <div class="span3 offset1">
                <img src="http://www.ubergizmo.com/wp-content/uploads/2011/11/17-LomoKino-Super-35.jpg" height="400px" width="300px">
              </div>
              <div class="span4 top-margin">
                <h2>Interested in new gear?</h2>
                <h4>Try out new gear before buying.  Renting through Gearlance gives you a chance to test the latest and greatest without spending a fortune.</h4>
              </div>
            </div>
          </div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
      </div>
    </div>
  </div>
  <div class="divide"></div>
  <div class="row fluid">
      <div class="span9 center">
        <h1 class="text-center">How does it work?</h1>
        <div class="row top-margin text-center">
          <div class="span3">
            <div class="camera"></div>
            <div>
              <h3>Take a look</h3>
              <p> Browse a huge selection of all kinds of gear.  Cameras, lenses, video, lighting, audio - all available for you to try out. Be inspired to try different kinds of gear.</p>
          </div>
          </div>
          <div class="span3">
            <div class="calendar"></div>
            <div>
              <h3>Reserve</h3>
              <p> Once you've found a piece of gear, easily send a rental request to the owner. Rates are clearly shown so there's no confusion about the cost of renting the gear.</p>
            </div>
          </div>
          <div class="span3">
            <div class="people"></div>
            <div>
              <h3>Make the exchange</h3>
              <p>Once you recieve the gear, pay for the rental through Gearlance.  No need to use another service like Paypal to wrap things up.  It's all in once place.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="span2 center">
        <%= link_to "Browse Gear", items_url, class: "btn btn-success btn-large" %>
      </div>
    </div>

<!-- <div class="row-fluid">  --> <!-- Slider row -->
	<!-- <div class="bxslider">
	  <% @items.sample(15).each do |item| %>

	  <a href="<%= item_url(item.id) %>">
		  <div class="slide crop">
			  <%= image_tag item.photo_url, width: 300,title: "#{item.name} | $#{item.daily_price} per day" %>
		  </div>
	  </a>
	  <% end %>
	</div>
</div> -->


<!-- Javascript for slider -->
<script type="text/javascript">
  $(document).ready(function(){
  $('.bxslider').bxSlider({
  	auto: true,
  	captions: true,
 	slideWidth: 300,
    minSlides: 1,
    maxSlides: 3,
    slideMargin: 10
  });
});
</script>

app/views/items/index.html.erb
<div class="row-fluid">
  <h1 class="withsubhead">Browse Gear.</h1>
  <h3>Try out gear from people like you.</h3>
</div>

<div class="row-fluid">
  <div class="span4 well">

      <%= notice %>

      <ul class="nav nav-list">  <!-- Categories list -->
        <li class="nav-header">Categories</li>
        <% @categories.each do |category| %>
          <li>
            <%= link_to category.slug.capitalize, category_url(category.slug) %>
            <% if category.subcategories.present? %>
              <ul class="sub_categories">
                <% category.subcategories.each do |subcat| %>
                   <li><%= link_to subcat.subname, category_url("#{category.slug}/#{subcat.subname}") %></li>
                <% end %>
              </ul>
            <% end %>
          </li>
        <% end %>
      </ul>

  </div>

  <div class="span8">

      <ul class="browse">
        <% @items.each do |item| %>
          <li class="item-list">
            <div class="row browse">
              <div class="span4">
                <% if item.image_content_type.present? || item.photo_url.present? %>
                  <% if item.image_content_type.present?  %>
                  <%= link_to image_tag(item.image.url(:small)), item_url(item.id) %>
                  <% else %>
                  <%= link_to image_tag(item.photo_url, class: "browse-image"), item_url(item.id) %>
                  <% end %>
                <% else %>
                  <%= link_to image_tag "http://www.clker.com/cliparts/J/P/C/M/k/d/teal-camera-md.png" %>
                <% end %>
              </div>
              <div class="span8 browse">
                <h3><%= link_to item.name, item_url(item.id) %></h3>
                <p><%= item.description[0..160] %>...</p>

                <p><b>Daily:</b> $<%= item.daily_price %> | <b>Weekly:</b> $<%= item.weekly_price %> | <b>Monthly:</b> $<%= item.monthly_price %></p>
                <div class="browse-buttons">
                  <% if signed_in? && item.user_id == current_user.id %>
                    <%= link_to "View", item_url(item.id), class: "btn" %> &nbsp;|&nbsp;
                    <%= link_to "Edit", edit_item_url(item.id), class: "btn" %> &nbsp;|&nbsp;
                    <%= link_to "Delete", item_url(item.id), method: :delete, confirm: "Do you really want to remove your #{item.name} and miss out on the opportunity to earn extra income?", class: "btn btn-danger" %>
                  <% else %>
                    <%= link_to "Reserve", item_url(item.id), class: "btn btn-primary" %>
                  <% end %>
                </p>
              </div>
            </div>

          </li>

        <% end %>
        </ul>
    </div>

</div>

<%= paginate @items %>

app/views/items/new.html.erb
<%= link_to raw("&laquo; Back"), items_url, class: "btn" %><br>

<br><h1>Add Your Gear</h1><br>



<%= render 'form' %>

app/views/items/show.html.erb
<div class="row">

  <div class="span8">
    <% if request.env["HTTP_REFERER"] == category_url(@item.category.slug) %>
      <%= link_to raw("&laquo; Back"), categories_url, class: "btn" %> &nbsp;
    <% elsif request.env["HTTP_REFERER"] == user_url(@item.user_id) %>
      <%= link_to raw("&laquo; Back"), user_url(@item.user_id), class: "btn" %> &nbsp;
    <% else %>
      <%= link_to raw("&laquo; Back"), items_url, class: "btn" %> &nbsp;
    <% end %>

    <% if signed_in? && @item.user_id == current_user.id %> | &nbsp;
      <%= link_to "Edit", edit_item_url, class: "btn" %>
    <% end %>

    <h1><%= @item.name %></h1>
    <p><b>Category:</b> <%= @item.category.name %> - <%= @item.subcategory.subname %></p>

    <p>
      <% if @item.image_content_type.present? || @item.photo_url.present? %>
        <% if @item.image_content_type.present?  %>
          <%= image_tag @item.image.url(:small) %>
        <% else %>
          <%= image_tag @item.photo_url, width: 300 %>
        <% end %>
      <% else %>
        <%= link_to image_tag "http://www.clker.com/cliparts/J/P/C/M/k/d/teal-camera-md.png" %>
      <% end %>
    </p>

    <h3>Description</h3>
    <p><%= @item.description %></p>
    <p><% if @item.reviews.count == 0 %>
      <h3>Be the first to review this gear</h3>
      <p>No review, no worries.  This is still a great piece of gear and may have just been added to our database. You can also check to see what other gear <%= link_to @item.user.first_name, user_url(@item.user_id) %> has on the site and the rating for those.</p>
      <% else %>
    <h3><%= @item.reviews.count %> Reviews from people like you rank this gear:  <%= @item.item_average_rating %> out of 5.0</h3>
        <% @item.reviews.reverse.each do |reviews| %>
      <p> Rating: <%= reviews.rating %> on <%= reviews.created_at.strftime('%B %d, %Y') %><br>
          <%= reviews.review %><br>
           <%= User.where(:id => reviews.reviewer_id)[0][:first_name] %> <%= User.where(:id => reviews.reviewer_id)[0][:last_name] %> <%= User.where(:id => reviews.reviewer_id)[0][:city] %>, <%= User.where(:id => reviews.reviewer_id)[0][:state] %><br>
        <% end %>
      </p>
      <% end %>
    </p>
  </div><!-- span8 -->

  <div class="span4">

    <div class="form-horizontal well">
      <%= notice %>
      <legend>Rent this Gear</legend>
      <p><b>Daily Price:</b> $<%= @item.daily_price %></p>
      <p><b>Weekly Price:</b> $<%= @item.weekly_price %></p>
      <p><b>Monthly Price:</b> $<%= @item.monthly_price %></p>
      <% if @item.reserved == true %>
        <p>* This item has been reserved for:<br>
          <% @item.reservations.each do |reservation| %>
            <%= reservation.start_date.strftime("%-m/%-d/%Y") %> - <%= reservation.end_date.strftime("%-m/%-d/%Y") %><br>
          <% end %>
        </p>
      <% end %>

      <!-- Button to trigger modal -->
      <% if signed_in? && @item.user_id == current_user.id %>
        <% elsif signed_in? && @item.user_id != current_user.id %>
        <a href="#myModal" role="button" class="btn btn-success" data-toggle="modal" style="margin-top: 10px;">Send Rental Request</a>
        <% else %>
        <%= link_to "Log In To Rent", new_session_url, class: "btn btn-success" %>
      <% end %>

      <!-- Modal -->
      <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">close ×</button>
          <h3 id="myModalLabel">Send Request</h3>
        </div><!-- end modal-header -->

        <div class="modal-body">
          <p>Hey <%= @item.user.first_name %>,</p>
          <p>I'm interested in renting your <%= @item.name %></p>

          <%= render 'date' %>

        </div><!-- end modal-body -->

        <div class="modal-footer">

        </div><!-- end modal-footer -->

      </div><!-- end myModal -->

    </div><!-- end form-horizontal -->


    <div class="well">
      <legend>About the Owner</legend>
      <div class="row">
        <div class="span2">
          <% if @item.user.avatar.present? %>
            <%= image_tag @item.user.avatar, width:125 %><br>
          <% else %>
            <%= gravatar_for @item.user, 125 %><br>
          <% end %>
        </div><!-- end span2 -->
        <h4><%= link_to "#{@item.user.first_name} #{@item.user.last_name}", user_url(@item.user.id) %></h4>
        <h5><%= @item.user.city %>, <%= @item.user.state %></h5>
      </div><!-- end row -->
      </br>

      <p>
        <% if signed_in? && @item.user_id == current_user.id %>
          <% if @item.user.user_bio.present? %>
              <%= @item.user.user_bio %>
          <% else %>
              Don't be shy... Let others see your good side. <%= link_to "Update Your Profile", edit_user_url(@item.user.id) %>
          <% end %>
          <% else %>
            <%= @item.user.user_bio %>
        <% end %>
      </p>

    </div><!-- well -->

  </div><!-- span4 -->
</div> <!-- row -->