config/routes.rb
Gearlance::Application.routes.draw do
  resources :reviews
  resources :subcategories
  get "/categories/:slug/:sub_category" => "subcategories#index"


  resources :tests


  root :to => "items#featured", as: "featured"

  resources :categories
  resources :items
  resources :users
  resources :reservations, except: [:new] do
    resources :charges
  end
  resource :session, except: [:edit]

  match "/faq" => "pages#faq"
  match "/about" => "pages#about"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gearlance</title>
    <%= stylesheet_link_tag    "application", "http://code.jquery.com/ui/1.10.3/themes/flick/jquery-ui.css", :media => "all" %>
    <%= javascript_include_tag "application", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js" %>
    <%= csrf_meta_tags %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-41014222-1', 'gearlance.com');
      ga('send', 'pageview');
    </script>
  <script>
    $(document).ready(function() {
      function modal() {
        $("#modal_overlay, #modal").fadeIn(300);
        $("body").css("overflow", "hidden");
        $(".close").click(function() {
          $("body").css("overflow", "auto");
          $("#modal_overlay, #modal").fadeOut(400);
        });
      }
      function GetCookie(name) {
        var arg = name + "=";
        var alen = arg.length;
        var clen = document.cookie.length;
        var i = 0;
        while (i < clen) {
          var j = i + alen;
          if (document.cookie.substring(i,j) == arg)
            return "here";
          i = document.cookie.indexOf(" ",i) + 1;
          if (i == 0) break;
        }
        return null;
      }
      var visit = GetCookie("FirstTime");
      if (visit == null){
         modal();
         var expire = new Date();
         expire = new Date(expire.getTime() + 7776000000);
         document.cookie = "FirstTime = here; expires = " + expire;
      }
    });
 </script>
</head>

<body>
  <div id="modal_overlay"></div><!-- end modal_overlay -->
  <div id="modal">
    <div id="m_message">
      <p>Hi!  Thanks for checking out Gearlance!  This beta is for <strong>demonstration purposes only.</strong></p> 
      <p>All of the data and listings that you see are fictional.  Feel free to look around, create a user, create listings, and reserve gear.</p>
      <p>We're hard at work on our public launch and would love your feedback.  E-mail us at <a href="mailto:contact@gearlance.com">contact@gearlance.com</a> if you want to get in touch.</p>
      <p>
      If you'd like to stay up-to-date with all Gearlance happenings, enter your e-mail below.
      </p>
      <!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="http://gearlance.us7.list-manage.com/subscribe/post?u=59b7951448d6df9e4e60d0f32&amp;id=df0f6483a6" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
<div class="mc-field-group">
  <label for="mce-EMAIL">Email Address:</label>
  <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
  <div id="mce-responses" class="clear">
    <div class="response" id="mce-error-response" style="display:none"></div>
    <div class="response" id="mce-success-response" style="display:none"></div>
  </div>  <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn button"></div>
</form>
</div>

<!--End mc_embed_signup-->
      <p>
      Thanks for stopping by!
      </p>
      <p>
      -Team Gearlance
      </p>
      <span class="close">Close</span>
    </div><!-- end m_message -->
  </div><!-- first time modal -->


  <div class="container"><!-- primary container -->
    <header class="row">
      <div class="span12">
        <div class="navbar navbar">
          <div class="navbar-inner">
            <div class="container" style="width: auto;">
              <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </a>
              <a class="brand" href="/"></a>
              <div class="nav-collapse">
                <ul class="nav pull-right">
                  <li><%= link_to "Browse", items_url %></li>
                  <li><%= link_to "List Your Gear", new_item_url %></li>
                  <% if signed_in? %>
                  <li><%= link_to "Dashboard", user_url(session[:user_id]) %></li>
                  <li><%= link_to "Log Out", session_url, method: "delete" %></li>
                  <% else %>
                  <li><%= link_to "Sign Up", new_user_url %></li>
                  <li><%= link_to "Log In", new_session_url %></li>
                  <% end %>
                </ul>
              </div><!-- /.nav-collapse -->
        </div>
      </div><!-- /navbar-inner -->
    </div><!-- /navbar -->
    </div>
    </header>

  <%= yield %>
  <div class="push"></div>
</div><!-- /primary container -->



<!-- Footer ================================================== -->
      <hr>
      <footer id="footer">
        <p class="pull-right"><a href="#top">Back to top</a></p>
        <div class="links">
          <a href="/about">About</a>
          <a href="/faq">FAQ</a>
          <a href="https://twitter.com/gearlance" target="new_window">Twitter</a>
          <a href="https://www.facebook.com/Gearlance" target="new_window">Facebook</a>
        </div>
      </footer>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>